services:
  bifrost:
    image: shridh0r/bifrost:latest
    container_name: bifrost
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=UTC
